// <auto-generated />
using System;
using AccountingOfAchievements.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingOfAchievements.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231230125447_edit")]
    partial class edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfReceiving")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssuedFromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IssuedFromId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Achievements", (string)null);

                    b.HasDiscriminator<string>("AchievementType").HasValue("Achievement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.AcademicAchievement", b =>
                {
                    b.HasBaseType("AccountingOfAchievements.Domain.Model.Achievement");

                    b.Property<string>("AcademArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Academic");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.ArtAchievement", b =>
                {
                    b.HasBaseType("AccountingOfAchievements.Domain.Model.Achievement");

                    b.Property<string>("AreaStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfCompet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Achievements", t =>
                        {
                            t.Property("AreaStage")
                                .HasColumnName("ArtAchievement_AreaStage");
                        });

                    b.HasDiscriminator().HasValue("Art");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.SportAchievement", b =>
                {
                    b.HasBaseType("AccountingOfAchievements.Domain.Model.Achievement");

                    b.Property<string>("KindOfSport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Sport");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Achievement", b =>
                {
                    b.HasOne("AccountingOfAchievements.Domain.Organization", "IssuedFrom")
                        .WithMany("Achievements")
                        .HasForeignKey("IssuedFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingOfAchievements.Domain.Model.Portfolio", "Portfolio")
                        .WithMany("Achievements")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedFrom");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Portfolio", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Organization", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
