// <auto-generated />
using System;
using AccountingOfAchievements.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingOfAchievements.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231120071905_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfReceiving")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IssuedFromOrganizationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AchievementId");

                    b.HasIndex("IssuedFromOrganizationID");

                    b.HasIndex("OwnerPortfolioId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Organization", b =>
                {
                    b.Property<Guid>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OgrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Achievement", b =>
                {
                    b.HasOne("AccountingOfAchievements.Domain.Organization", "IssuedFrom")
                        .WithMany("Achievements")
                        .HasForeignKey("IssuedFromOrganizationID");

                    b.HasOne("AccountingOfAchievements.Domain.Model.Portfolio", "Owner")
                        .WithMany("PersonalPortfolio")
                        .HasForeignKey("OwnerPortfolioId");

                    b.Navigation("IssuedFrom");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Model.Portfolio", b =>
                {
                    b.Navigation("PersonalPortfolio");
                });

            modelBuilder.Entity("AccountingOfAchievements.Domain.Organization", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
